name: ArbiHunter Feature Action
description: Controls development workflow
author: TheArbiHunter Team

inputs:
  CONFIGURATION:
    description: JSON Feature configuration
    required: true
  CLOUDFLARE_API_EMAIL:
    description: CloudFlare API Email
    required: true
  CLOUDFLARE_API_TOKEN:
    description: CloudFlare API Token
    required: true
  CLOUDFLARE_ZONE_ID:
    description: CloudFlare Zone ID
    required: true
  CLOUDFLARE_DOMAIN:
    description: CloudFlare Domain
    required: true
  KUBERNETES_ADDRESS:
    description: Kubernetes Ingress Public Address
    required: true

outputs:
  IS_PRODUCTION:
    description: Is production environment
  FEATURE:
    description: TheArbiHunter feature name
  NAMESPACE:
    description: TheArbiHunter namespace name
  DATABASE:
    description: Google Cloud Postgres DB name
  BACKEND:
    description: Backend domain
  FRONTEND:
    description: Frontend domain
  PAYMENT:
    description: Payment domain
  ADMIN:
    description: Admin domain

runs:
  using: node20
  main: dist/index.cjs
