name: ArbiHunter Feature Action
description: Controls development workflow
author: TheArbiHunter Team

inputs:
  TYPE:
    description: Action type
    required: true
  CLOUDFLARE_API_EMAIL:
    description: CloudFlare API Email
    required: true
  CLOUDFLARE_API_TOKEN:
    description: CloudFlare API Token
    required: true
  CLOUDFLARE_ZONE_ID:
    description: CloudFlare Zone ID
    required: true
  CLOUDFLARE_DOMAIN:
    description: CloudFlare Domain
    required: true
  KUBERNETES_ADDRESS:
    description: Kubernetes Ingress Public Address
    required: true

runs:
  using: node20
  main: dist/index.cjs
