name: ArbiHunter Feature Action
description: Controls development workflow
author: TheArbiHunter Team

inputs:
  TYPE:
    description: Action type
    required: false
  CLOUDFLARE_API_EMAIL:
    description: CloudFlare API Email
    required: false
  CLOUDFLARE_API_TOKEN:
    description: CloudFlare API Token
    required: false
  CLOUDFLARE_ZONE_ID:
    description: CloudFlare Zone ID
    required: false
  CLOUDFLARE_DOMAIN:
    description: CloudFlare Domain
    required: false
  KUBERNETES_ADDRESS:
    description: Kubernetes Ingress Public Address
    required: false
  TELEGRAM_TOKEN:
    description: Telegram Feature Bot Token
    required: false
  TELEGRAM_CHAT_ID:
    description: Telegram Feature Chat ID
    required: false
  MESSAGE:
    description: Telegram Message
    required: false

runs:
  using: node20
  main: dist/index.cjs
