#!/usr/bin/env sh

# Run prettier and eslint
bun run format
bun run lint:fix


# Build action and add to commit
bun run build
git add dist

# Update package version and add to commit
npm version patch --no-git-tag-version
git add package.json

